nicknames = {
  "hammers": "Fear Grips World As \"Worthy\" Terrorize Cities",
  "cubes": "Struggle for the Cube Continues",
  "H4H": "Heroes for Hire",
  "GR": "Ghost Rider",
  "M.o.d.o.k": "Modok",
}

secures = {
    "Cosmic Invasion! Black Order Descends on Earth",
    "Deadly Meteors Mutate Civilians",
    "Demons Downtown! Has Our Comeuppance Come Due?",
    "Gamma Wave Sweeps Across Midwest",
    "Infinity Formula Goes Missing!",
    "Intrusions Open Across City as Seals Collapse",
    "Mayor Fisk Vows to Find Missing Witnesses",
    "Mutant Madman Turns City Center Into Lethal Amusement Park",
    "Portals Overrun City With Spider-People!",
    "Riots Spark Over Extremis 3.0",
    "Super-Powered Scoundrels Form Sinister Syndicate!",
    "SWORD Establishes Base On Moons Blue Area",
    "Terrigen Clouds Sweep Over City"
}

extracts = {
    "Alien Ship Crashes in Downtown!",
    "Deadly Legacy Virus Cured?",
    "Fear Grips World As \"Worthy\" Terrorize Cities",
    "Mutant Extremists Target U.S. Senators!",
    "Mystic Wakandan Herbs: Fact or Fiction?",
    "Panic Grips City As Evacuation Efforts Continue!",
    "Research Station Attacked!",
    "Skrulls Infiltrate World Leadership",
    "Spider-Infected Invade Manhattan",
    "Struggle for the Cube Continues",
    "The Montesi Formula Found"
}

characters = {
    "Black Panther",
    "Killmonger",
    "Venom",
    "Okoye",
    "Vision",
    "Winter Soldier",
    "Thor, Prince of Asgard",
    "Hela, Queen of Hel",
    "Nebula",
    "Black Dwarf",
    "Drax The Destroyer",
    "Black Widow Agent of S.H.I.E.L.D",
    "Ronan the Accuser",
    "Hawkeye",
    "Spider-Man (Miles Morales)",
    "Ghost-Spider",
    "Wong",
    "Doctor Strange",
    "Punisher",
    "Taskmaster",
    "Daredevil",
    "Wasp",
    "Ant-Man",
    "Sabretooth",
    "Wolverine",
    "Baron Zemo",
    "Black Widow",
    "Crossbones",
    "Doctor Octopus",
    "Red Skull",
    "Spider-Man",
    "Captain America (Sam Wilson)",
    "Captain Marvel",
    "Iron Man",
    "Ultron",
    "Valkyrie",
    "Loki, God of Mischief",
    "Corvus Glaive",
    "Proxima Midnight",
    "Gamora",
    "Groot",
    "Rocket Raccoon",
    "Star-Lord",
    "Ebony Maw",
    "Green Goblin",
    "Infinity Gem: Mind",
    "Infinity Gem: Power",
    "Infinity Gem: Reality",
    "Infinity Gem: Soul",
    "Infinity Gem: Space",
    "Infinity Gem: Time",
    "Thanos, The Mad Titan",
    "Ghost Rider",
    "Angela",
    "Enchantress",
    "Kingpin",
    "Bullseye",
    "Dormammu",
    "Black Bolt",
    "Medusa",
    "Crystal",
    "Lockjaw",
    "Amazing Spider-Man",
    "Black Cat",
    "Captain America (Steve Rogers)",
    "War Machine",
    "She-Hulk",
    "Hulk",
    "Cyclops",
    "Storm",
    "Magneto",
    "Toad",
    "Beast",
    "Mystique",
    "Bob, Agent of Hydra",
    "Deadpool",
    "Mr. Sinister",
    "Cable",
    "Domino",
    "Blade",
    "Moon Knight",
    "Iron Fist",
    "Luke Cage",
    "Mysterio",
    "Carnage",
    "Modok",
    "Hulkbuster",
    "Cassandra Nova",
    "Jean Grey",
    "Omega Red",
    "Nick Fury",
    "S.H.I.E.L.D. Agents",
    "Juggernaut",
    "Colossus",
    "Magik",
    "Kraven the Hunter",
    "Lizard",
    "Gambit",
    "Rogue",
    "Sin",
    "Viper",
    "Ms. Marvel",
    "Quicksilver",
    "Scarlet Witch",
    "Ancient One",
    "Baron Mordo",
    "Doctor Voodoo",
    "Hood",
    "Clea",
    "Doctor Strange, Sorcerer Supreme",
    "Honey Badger",
    "X-23",
    "Elektra",
    "Shadowland Daredevil",
    "Hand Ninjas",
    "Shuri"
}

tactics = {
    "Avengers Assemble",
    "Brace for Impact",
    "Cosmic Invigoration",
    "Dark Reign",
    "Disarm",
    "Drop Off",
    "Escort to Safety",
    "Follow Me",
    "Heave Ho",
    "Inspiring Monologue",
    "Mission Objective",
    "One-Two Punch",
    "Patch Up",
    "Ricochet Blast",
    "Sacrifice",
    "Second Wind",
    "Smash",
    "Sucker",
    "The Age of Ultron",
    "Trip Up",
    "Anger Management",
    "Gamma Launch",
    "Seeing Red",
    "A.I.M. Lackeys",
    "Psychic Fortress",
    "Recalibration Matrix",
    "Battle Lust",
    "Usurp the Throne",
    "Wakanda Forever",
    "Advanced R&D",
    "Vibranium Shielding",
    "Lethal Protector",
    "Uneasy Allies",
    "All Webbed Up",
    "All You've Got",
    "Web Barrier",
    "Odin's Blessing",
    "Thunderwave",
    "Doomed Prophecy",
    "Sibling Rivalry",
    "Field Dressing",
    "Psychic Shielding Device (P.S.D.)",
    "Tactical Analysis",
    "Till the End of the Line",
    "Blood to Spare",
    "Execute",
    "Price of Failure",
    "Daughters of Thanos",
    "Medpack",
    "Deadly Duo",
    "We Are Groot",
    "Crew of the Milano",
    "Rocket Boots?!",
    "Marked for Death",
    "Mothership",
    "Shhh...",
    "No Matter the Cost",
    "Unearthly Rage",
    "Blind Obsession",
    "Well-Laid Plans",
    "Pentagram of Farallah",
    "Seven Suns of Cinnibus",
    "Vapors of Valtorr",
    "Heavy Firepower",
    "Professionals",
    "Face Me",
    "Power of the Cosmos",
    "No Escape",
    "Pym Particles",
    "Reversal",
    "Deal With the Devil",
    "Highway to Hell",
    "Grievous Wounds",
    "Lovable Misfits",
    "Rainbow Bridge",
    "All According To Plan",
    "Hired Muscle",
    "Shadow Organization",
    "Acute Senses",
    "Climbing Gear",
    "Cruelty",
    "Heavy Ordinance",
    "Blood Red and Personal",
    "Extreme Conditioning",
    "Dark Empowerment",
    "Dark Restoration",
    "Attilan Rising",
    "Inhuman Royal Family",
    "Terrigenesis",
    "Bitter Rivals",
    "Elemental Infusion",
    "Last-Minute Save",
    "Aunt May's Wheat Cakes",
    "Spider-Tracker",
    "The Cat and the Spider",
    "Bird of Prey",
    "Eyes on the Prize",
    "Tactical Maneuvers",
    "The Air Force",
    "A-Force Assemble!",
    "Agents of S.M.A.S.H.",
    "Special Delivery",
    "Stalwart Determination",
    "Weapon X Program",
    "X-Ceptional Healing",
    "Children of the Atom",
    "First Class",
    "To Me My X-Men",
    "Asteroid M",
    "Magnetic Crush",
    "Magnetic Refraction",
    "Deception",
    "The Books of Truth",
    "Chimichangas",
    "Pretty Sneaky, Sis",
    "Yoink",
    "Cloning Banks",
    "Forced Extraction",
    "Cat and Mouse",
    "Dirty Work",
    "Warpath",
    "Banishment",
    "Bats the Ghost Hound",
    "Siege of Darkness",
    "Heroes for Hire",
    "K'un-Lun Training",
    "Kick 'em While They're Down",
    "Carnage Rules",
    "The Grand Illusion",
    "There Will Be Carnage",
    "Fall Back",
    "Helios Laser Bombardment",
    "Jean!!!",
    "Mental Domination",
    "Carbonadium Synthesizer",
    "Red Room Training",
    "Battlefield Medicine",
    "Defensive Prototype",
    "Eye In The Sky",
    "Hard Reset",
    "Helicarrier Strike",
    "Life Model Decoy",
    "Reposition",
    "Sitrep",
    "The Initiative",
    "The Shieldmobile",
    "Do You Know Who I Am?",
    "Makin' A Ruckus",
    "Versatile Strategy",
    "Fastball Special!",
    "Indomitable",
    "Journey Through Limbo",
    "Fearful Symmetry",
    "Monkey Brain Is Lizard Home",
    "Neogenetic Recombinator",
    "Sinister Traps",
    "Charming Thief",
    "Dark Past",
    "Mind If I Cut In?",
    "Pardon Me, Sugah",
    "Illicit Tech",
    "To Ash and Cinder",
    "A Better Tomorrow",
    "Fan Club",
    "Can I Borrow That?",
    "Difficult To Please",
    "No More Mutants",
    "The Whims of Chaos",
    "Astral Ring",
    "Bane of Damballah",
    "Orb of Agamotto",
    "Hood's Gang",
    "Plane of Pohldahk",
    "Seance",
    "Book of Cagliostro",
    "Iron-Bound Books of Shuma-Gorath",
    "Wand of Watoomb",
    "The Bar With No Doors",
    "Jonathan the Unstoppable",
    "Wolverines",
    "Bounty Hunters",
    "Cruel Tutelage",
    "No Mercy",
    "Shuriken Arashi",
    "Vendetta",
    "The Bar With No Doors (Reverse)"
}